name: itmo-golang-computation-2025

services:
  http:
    container_name: app-http
    build: .
    environment:
      SERVER_TYPE: http

  grpc:
    container_name: app-grpc
    build: .
    environment:
      SERVER_TYPE: grpc

  nginx:
    container_name: app-nginx
    image: nginx:1.27.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - http
      - grpc