// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calculate": {
            "post": {
                "description": "This endpoint takes a calculation request and returns the result of the calculation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculation"
                ],
                "summary": "Calculate result based on input parameters",
                "parameters": [
                    {
                        "description": "Calculation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CalcRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful calculation result",
                        "schema": {
                            "$ref": "#/definitions/model.SolutionResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.Operation": {
            "type": "object",
            "properties": {
                "left": {
                    "type": "string"
                },
                "op": {
                    "type": "string"
                },
                "right": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "var": {
                    "type": "string"
                }
            }
        },
        "model.CalcRequest": {
            "type": "object",
            "properties": {
                "operations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Operation"
                    }
                }
            }
        },
        "model.Operation": {
            "type": "object",
            "properties": {
                "left": {
                    "type": "string"
                },
                "op": {
                    "type": "string"
                },
                "right": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "var": {
                    "type": "string"
                }
            }
        },
        "model.PrintResult": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                },
                "var": {
                    "type": "string"
                }
            }
        },
        "model.SolutionResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PrintResult"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
