// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/calculation.proto

package app

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SolverSvc_Solve_FullMethodName = "/service.SolverSvc/Solve"
)

// SolverSvcClient is the client API for SolverSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolverSvcClient interface {
	Solve(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*SolutionResponse, error)
}

type solverSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewSolverSvcClient(cc grpc.ClientConnInterface) SolverSvcClient {
	return &solverSvcClient{cc}
}

func (c *solverSvcClient) Solve(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*SolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SolutionResponse)
	err := c.cc.Invoke(ctx, SolverSvc_Solve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolverSvcServer is the server API for SolverSvc service.
// All implementations must embed UnimplementedSolverSvcServer
// for forward compatibility.
type SolverSvcServer interface {
	Solve(context.Context, *CalcRequest) (*SolutionResponse, error)
	mustEmbedUnimplementedSolverSvcServer()
}

// UnimplementedSolverSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolverSvcServer struct{}

func (UnimplementedSolverSvcServer) Solve(context.Context, *CalcRequest) (*SolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Solve not implemented")
}
func (UnimplementedSolverSvcServer) mustEmbedUnimplementedSolverSvcServer() {}
func (UnimplementedSolverSvcServer) testEmbeddedByValue()                   {}

// UnsafeSolverSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolverSvcServer will
// result in compilation errors.
type UnsafeSolverSvcServer interface {
	mustEmbedUnimplementedSolverSvcServer()
}

func RegisterSolverSvcServer(s grpc.ServiceRegistrar, srv SolverSvcServer) {
	// If the following call pancis, it indicates UnimplementedSolverSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SolverSvc_ServiceDesc, srv)
}

func _SolverSvc_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolverSvcServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolverSvc_Solve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolverSvcServer).Solve(ctx, req.(*CalcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SolverSvc_ServiceDesc is the grpc.ServiceDesc for SolverSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolverSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.SolverSvc",
	HandlerType: (*SolverSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Solve",
			Handler:    _SolverSvc_Solve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/calculation.proto",
}
