name: Run Tests

on:
  push:
    branches:
      - main
      - dev/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          make deps

      - name: Build project
        run: |
          make build

      - name: Run tests
        run: |
          make test

      - name: Lint
        if: ${{ success() }}
        run: |
          make lint